export const styles = {
    colors: {
        backgroundMain: "#e4f6fc",
        backgroundSurface: "rgba(0, 166, 255, 0.15)",
        textMain: "#2c9be0",
        textMuted: "#2c9be099",
        textBrightMain: "#e4f6fc",
        textBrightMuted: "#e4f6fc99",
        border: "#2c9be0",
        button: "#2c9be0",

        error: "#EF4444",
        errorBack: "#ffeaea",
        warning: "#F59E0B",
        warningBack: "#fff5e3",
        info: "#2c9be0",
        infoBack: "#ddf2ff",
    },
    radius: {
        xxs: 2,
        xs: 4,
        sm: 8,
        md: 12,
        lg: 16,
        xl: 20,
        xxl: 24,
    },
    spacing: {
        xxs: 4,
        xs: 8,
        sm: 12,
        md: 16,
        lg: 24,
        xl: 32,
        xxl: 40,
    },
};
